### PR TITLE
Term regex

### PR DESCRIPTION
**Pull request by pkarman**
allow term rule to be configurable at run time.

### CODE REVIEW

**Comment by pkarman** [comment]
@zerowidth can I get a review of this PR please?

**Comment by zerowidth** [comment]
Hmmm, I like the suggestion from #3 -- wildcards are always valid as terms, I'd think, and I'd rather see direct support for it rather than requiring a user to configure the library with an easy-to-get-wrong regex.

**Comment by pkarman** [comment]
In my apps, I do this:

```
LuceneQueryParser::Parser.new :term_re => "\\p\{Word\}\\.\\*\\-\\'"
```

which supports full UTF-8 range (the \w does not), as well as domain names (the dot), dashes and contractions (single quote). I need to be able to support the custom analyzers on the server side of a Lucene (in our case ES) instance.

How about both: incorporate the wildcard and "special" chars from #3 and also allow for custom regex for advanced users?

**Comment by zerowidth** [comment]
> How about both: incorporate the wildcard and "special" chars from #3 and also allow for custom regex for advanced users?

:thumbsup: I like that idea. The default would ideally be as close to the (un-detailed, when I was working on this) spec as possible, but letting you add the custom bits you need sounds just fine too.

**Comment by pkarman** [comment]
superceded by #9

**Pull request closed without merging**
