### PR TITLE
Wildcards and term regex

### PR DESCRIPTION
**Pull request by pkarman**
This PR combines #2 #3 and #8 in a single branch.

### CODE REVIEW

**Comment by lukaszkorecki** [comment]
Overall this looks like a better implementation, however (there's always one _however_ ;-)) - I think it would be great to have the infromation about the term being a wildcard term available in the AST. With these changes I'd have to check for presence of `*` in every term.

(I wrote a tiny evaluator of these rules in Ruby - which basically gives me search capabilities similar to Lucene/Elasticsearch but for Ruby strings - I want my users to be able to specify only valid queries)

I know it's a bit specific use case - I'd assume majority of users of this gem use the command line interface, whereas my code integrates directly with `LuceneQueryParser::Parser` class.

**Comment by pkarman** [comment]
How should a search term like `fo*bar` be evaluated?

https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Wildcard Searches

I see from those docs we should also support the `?` character.

**Comment by lukaszkorecki** [comment]
Ah, I missed that one - if that's the case checking for presence of `*` and `?` should be enough.

**Comment by pkarman** [comment]
@zerowidth ready for your review. I added support for `?` and `*` both.

**Comment by maherbeg** [comment]
Super :+1: to this. Would it be possible to get this merged?

**Comment by pkarman** [comment]
@zerowidth I have the power to click the Big Green Button but would prefer not to merge my own PRs. Care to do the honors?

**Comment by zerowidth** [comment]
:thumbsup: sorry for the delay, this looks good. Thanks!

**Pull request merged**
